---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: auto-scaler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: auto-scaler
      version: 9.x.x
      sourceRef:
        kind: HelmRepository
        name: auto-scaler
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    cloudProvider: aws
    replicaCount: 3
    # affinity -- Affinity for pod assignment
    affinity: { }

    # additionalLabels -- Labels to add to each object of the chart.
    additionalLabels: { }

    vpa:
      # vpa.enabled -- If true, creates a VerticalPodAutoscaler.
      enabled: true
      # vpa.updateMode -- [UpdateMode](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler/v0.13.0/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L124)
      updateMode: "Auto"
      # vpa.containerPolicy -- [ContainerResourcePolicy](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler/v0.13.0/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L159). The containerName is always et to the deployment's container name. This value is required if VPA is enabled.
      containerPolicy: { }


    autoDiscovery:
      # cloudProviders `aws`, `gce`, `azure`, `magnum`, `clusterapi` and `oci` are supported by auto-discovery at this time
      # AWS: Set tags as described in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup

      # autoDiscovery.clusterName -- Enable autodiscovery for `cloudProvider=aws`,
      # for groups matching `autoDiscovery.tags`.
      clusterName: home-kubernetes # cluster.local

      # autoDiscovery.tags -- ASG tags to match, run through `tpl`.
      tags:
        - k8s.io/cluster-autoscaler/enabled
        - k8s.io/cluster-autoscaler/home-kubernetes
      # - kubernetes.io/cluster/home-kubernetes

      # autoDiscovery.roles -- Magnum node group roles to match.
      roles:
        - worker

    # awsAccessKeyID -- AWS access key ID
    # ([if AWS user keys used](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#using-aws-credentials))
    awsAccessKeyID:
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: aws_access_key_id

    # awsSecretAccessKey -- AWS access secret key
    # ([if AWS user keys used](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#using-aws-credentials))
    awsSecretAccessKey:
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: aws_secret_access_key

    # awsRegion -- AWS region (required if `cloudProvider=aws`)
    awsRegion:
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: aws_region
