apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:+9AZG6rDBZid2gmFCwUaMq+Pt6A=,iv:+QlaxOKjKezPXEabJZoMnRnYmYketAiq7MgyRzXI7oY=,tag:M5vFkGc9Bf40Q0fOfT/V0Q==,type:str]
    aws_region: ENC[AES256_GCM,data:wJSzo+ExUi4C,iv:b2qrbtqK/pQ9csE2qQiJqBQhHfr2hNFFDDYVQZgVjL8=,tag:TSvC8SH7ovJGkKD/0+DeFQ==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:d4a/VtmErmm0tqmQYS3HssG84Y9RpoB6LTBdjF+2YBHTQUL2mxImbA==,iv:xrLIYmDdPTT4mljPeUy3T+Y5jvx1cQrlNYCOVLKJle4=,tag:NoySUu3Tczxi59CfHXTSiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1584w9hjcuz39gn5rkz0qczhe9gwqlkvjvag6njs62k6pv2sr4q4se59ys2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWjYzaXNkK2Nad0p3UHdi
            MGdXRis5WEt4NWozbWRkcWQ4Tktnc2lTakYwCjg0bHFuSjRpeXlSMGgwYjNVMFNx
            V3ErNkl1QXpVM1UrNHZjTndWV3RSQ2sKLS0tIEw5Z2JRMW5NaWRoY00rNGk4Y0dG
            OWhhQXEwY0p6TFdqYUgxcjVMcENvRGMKm4c5ZxiwNMUq/MCPJ6ITd+qehMtYkBmX
            d0/K3gFcq3G03t+D24w6+JsRlRaUo97QrvfTW5CloHAeu6hgA+0UKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T17:44:22Z"
    mac: ENC[AES256_GCM,data:1IG9u8XqLRUfV2V1TgNVXojo30AtAHi3tuhrRGhLl9mmBtkqOxh/AevEZEvou1tIjFqxAvIMvUdbxIfpjMdTbzL32AouOIyyI7n8fDp6USImxLq0sINIJoy6AYyyaqJDnz5/Ovpi197uxh9Z57SAacOSzNvcTJYI8F7IlQfmBMQ=,iv:mO9bvz2U0HZiUecOD4AQe+djGzlvBmGLW3hdanjgJ5s=,tag:8Fo8tc7Jq0cHf0nbwBPkGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
