ansible_become_pass: ENC[AES256_GCM,data:z0Q58P230Uw=,iv:TIn97WkhPSJsnNBisAYuywtkKWoppcxrOW8cNIAMf0c=,tag:2C4hedJir47DLg8t1fNFPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1584w9hjcuz39gn5rkz0qczhe9gwqlkvjvag6njs62k6pv2sr4q4se59ys2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNU1uWEFrWko4c2RYUW54
            NUFoYjh4aWpoWHJ4eGNvYlFVV2xCV2RwVTE0CkJDMDN6MnAya0lNVnRjZnBzczZk
            N2J5SzRUTVA2Z2FUYmRMOUtkdkRzMm8KLS0tIHRLNUVkQm5lTEpvWUQzeUoybC96
            NzJPZjJtb0ZTSTkvVE14MGF4SWJwbHcKvtcfA29wN7EkY7I05uuRpqzVjD/fsps/
            ZFGNDmS8bEj/8xEEZD+lRbFsLB2IYOlMG6UB4clhRqjMrgTZJnnwvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T15:25:13Z"
    mac: ENC[AES256_GCM,data:/GY4aXe8lRmkOGtRzzzgM9CALneF0MIKDUx0EOY0xHrr6m7t4SIKsjK6aA06cw3J3hiMB0h1zhnbnozHCNDcgH6tWK9EyOJ4Ded8ibO00+l5ZX1tX7DMzhjVQxZeCqcQJ8wSMSoAzXT48R7hw5t4sKkk/wmoWOjxGPCTAVrUC4c=,iv:5ahFeSzDQC9gH5X+6HapihlDNnBsvx068EEyyzc4PM4=,tag:Q5/wDdRgGt6H9EHTAJVeJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
