ansible_become_pass: ENC[AES256_GCM,data:x5UCBcAiJf8=,iv:v2GxCvBXzX7AfLjGsWqF6PP+B+153cBJrQJUa3uFmcE=,tag:Vg1UlzMbAtzAhmWV4hf0EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1584w9hjcuz39gn5rkz0qczhe9gwqlkvjvag6njs62k6pv2sr4q4se59ys2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd2xOUFpyNjNEL2lISk9U
            SFA0SVJqeWFMTktPdTZSRWNTOTBzc0wxR0I0ClFmdVRxL1owRG1qaVh2a3BXTENp
            QktuNDVyMXlFWVRRNk81dVdPQ3pqaEkKLS0tIGp5M2pRNmtnVytHcTM0SkxuQVp2
            QnRMak5EenJDOUIyTHhaRGo4R2RLb0kKvkKdsgZklJy+HaqEq3UD6CR6ouixARq/
            4p3Vc8Y4/u1fszLnzkvBAXmGqqPR7C0DCHFQo4pUSnCc+BsfCN0WPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T17:42:47Z"
    mac: ENC[AES256_GCM,data:3F6hJgPc6qYe80fSxga6qh99KdJObctUhSlsBqBqq5nNUhaOuQb7bugz2TxfhfvtYEiXBPm5WmEz3Ds4cVlsQdftDlMKyBIA4TS84SZFBny+PqKFzEy+JghX2pazAPP8dz5EKi65sSGb5SHISXkRpSrQsK+YRTEqYlLlUktI7AU=,iv:n4IYuPHy52KZYAOADMQjtYF2IcLU5/XNp3h+lqizlng=,tag:pHb6eYbO4yYzaMqciLnkcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
