ansible_become_pass: ENC[AES256_GCM,data:PfVIy/dXvVQ=,iv:dZTJRIq4sMkIWT3hs76ZG3DBR+Eqb4qLCQT+Zr5RGC0=,tag:MTt4FXDtZTjbVHGjNxCxVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1584w9hjcuz39gn5rkz0qczhe9gwqlkvjvag6njs62k6pv2sr4q4se59ys2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTjBnRGJqNVVnTnRpSWxz
            bVhWT2laWWhlZGtaT29tU1E1OGQvRlVBMWpRCkNCZitMZmNVSE9kYTl1Q2R0YzYr
            dlkyV3JsK1JqRStPclg5aGhnZXhIMDQKLS0tIGdYcG9mbmdYUkJZSUczeDJaNjl3
            cGp4UzExaUdPS1FiT3dWVExNYVhzWVEKTFd8HqAekrMieLpwO2xQ4uiYbfOdypOc
            6AYM7P7x17pJXx9ehQZyl36rgMqoFQv4o1VPvS9iST3HsjqZMn7SVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T17:42:50Z"
    mac: ENC[AES256_GCM,data:30r31jojx7/SstPQXYBN8kAjzrLNdRZ7n0302Yd6Kt4og+/lkts6vsr1IhWAXBQa8GZ2vWPgu7SrXZW509S9IqbrUhRe39dN4W0btxhsEmPK+yMmmlklE8fVLyOhh3q6YJ4qktj5y3I/RuGZcSA2re1B9kpD/nQUN6H/ho1dEyU=,iv:3cqN5vsM+2Lb7xmDeUp36fAXDH+U2T5BezMcGX/3uoA=,tag:FuGQ5QpjEQbgHWhwPtDGkg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
