ansible_become_pass: ENC[AES256_GCM,data:j1tiofJNMJs=,iv:uJtDaW8sbKfoRU/L0mnQnga8FFQFTMC07v2uYSOesEg=,tag:WB3lWRxBJ6QhnTDmLGwXWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1584w9hjcuz39gn5rkz0qczhe9gwqlkvjvag6njs62k6pv2sr4q4se59ys2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUEgwL0RnbGRDR0ZtZVFK
            dFh1N0hkZGdkWWJwV24xb1ErQkFIc3UvQWhVCjFXWkVaQU0wZlpEOXlMYnpPdndi
            RWNhWG82RTJVWDFWcUJZTFpnRVdOKzQKLS0tIFFXTHFGclZscWVxaVgrOHpIMHdT
            VlpJbzdrMUZaVTQyZVZCUmpyckxRM2cKG4tTLZ6YBQAH7X1lqlHKIfzRjXhRDZiZ
            jtTMkUpt93nUNQUA0DL+BhMQlqf4cDZAxbt4Wcoi3h5RIXCOHZzMmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T15:25:15Z"
    mac: ENC[AES256_GCM,data:zjGAIk+9OyuSSuRbw3g7gztIqmsckQ8ojUXEVBCFunPeaw4mfjjN1olCe3AznBJ/hthDn84MNbth2AUPmJhzQcPRmJQp9XUnaCHrRskuJ2CFvehwM05nkcNw4aZi08kE4ObMYVIboVZ+f3TChzn3lMBYQgFmBksAMgiR1HImhgs=,iv:XHe7TVfDA321/WVzGlxMfvbtiX6XGrymwbnIYyFEJTA=,tag:2vRiTNmcZj9Z9bkOehuHzg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
