ansible_become_pass: ENC[AES256_GCM,data:khhhpuD8SzQ=,iv:kodeD4fy61CbpD237paVyFE5DVIJsdX3RRImJ8VlGsU=,tag:95gqQmrECykulYJZGkzLGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1584w9hjcuz39gn5rkz0qczhe9gwqlkvjvag6njs62k6pv2sr4q4se59ys2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBackx4bExpZlJ5NXJWU2FE
            R3R6OHFmaUNMdEJDZEFsenhEcXI5cTV4d0JnCkFOWC9rNFNTVlA2L0RvbTR3eCtN
            eE9nRnZveFpiS2hCZ09ERFRNWlBaek0KLS0tIEw5eWw4aXdtUG9oby9wamcvY1Iz
            VHNUWVpkVXdTOXllamdjMzBUSFoxeEEKp74FFz73dTXRxD8OSQ66t1Pkw2gr0xtJ
            6tjKRES3RtTgdq0lnxKFUrA/sbeYGdHJzKzYYXwuydlI1KxJeVorKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T17:42:48Z"
    mac: ENC[AES256_GCM,data:dP0S5/A5DYXNtHeh+UwuVee9RPlewsYT7O2keHBRa13t973WtkAcOiOQrOv8gYgsagV+4NsRXy9ouuALi+DDi7N26an3WIfHCIG9vdT0xJSzG9KhcLBMSlNxn0D6anT/rSwnMOuPehxxrHPrbaI/zhCoR+ZO1VEBN9TD5j6HSj8=,iv:uWr5cktWoHz2+5atKfs9oSOygE3OnkpceSArPgWDc5Y=,tag:H4cY4ckESsDueK1nwuRJJw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
