apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:eYy5a8ic+qXPziItiic=,iv:josL5lytlUZjKlHWvX+rVvvBGVMQz6i7sHr9EQoWGCU=,tag:+FykBAS82cOIJtv/x2WM+A==,type:str]
    admin-user: ENC[AES256_GCM,data:AGj+pJM=,iv:XQNnIykZyVov9H4PrTTCW+avn1zWRBllzVoTG5EuU0U=,tag:KYrKxeqoGIWiv6MCW8lN/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1584w9hjcuz39gn5rkz0qczhe9gwqlkvjvag6njs62k6pv2sr4q4se59ys2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdUxLMndQREgwaWFlekVX
            ZUo1QnZUQUZVTmN4YS9TeFVpU01jOGxkYkdBCnBOSUlndEFsdWxScEEydnNKK1kr
            WlNVSExzaXRHZ2Y4TzBXdXd4RDNEQkkKLS0tIFdrYndmQVBlZm1jVTNMdTNSQ29V
            dHdIOWpTMEpiYmpscGV3blRCSDF4NXcK+WC+LKh/+avcrtu2q1rjf+BIqf/G7gx1
            tLhnhPxT/YXeUJTObeuwLhpwv4WYj7HuM4p+7NdduiVRu4CcyKx+AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T15:26:57Z"
    mac: ENC[AES256_GCM,data:Z3W40ZyI+NIPioaurIoyqNAGHSEF2kGgXdXUROq/Tqh4UqqcRgai/dDbfZZARIq+WSGSQU6FmbS6IFilMCJQRMpMYCcEgYZJ1NWyouseW6THYGSO0uEOd3Q0c4LEv1SJQA/k0n8QFK9yE5Z0y7knf+WhmOubYWlP5V1VkvPC6PM=,iv:HfevOwBAYBimjchj2rfCQCwETDkqSLSUSqDHAN76cL8=,tag:cZJ2USxKkiOfi6KDYK8j1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
