apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:PGmC3eAmCNhZrvBk,iv:OqqT6zdRNU0swZt7k2Mpxyw0bEub3CnmXC4F/1ePn78=,tag:56rTfBzPHPPreqEb2MVFhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1584w9hjcuz39gn5rkz0qczhe9gwqlkvjvag6njs62k6pv2sr4q4se59ys2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSEN0c2JRMzhpQkRHRW1T
            WTdndEhaektuL2FKbCtHdEhBcXVrOWlJL1RZClR4c2RRUDUvdmJaSUEvS1A4Zitz
            RE1NRUpDdXZzV0xsVjBydDZiY244dUUKLS0tIGU4SHRVMmdmZnhweWhPN1BtNVFQ
            T2VqcEpLdHNsTXZXeDUyNm9XOEYzNnMKwzHH2fG761je4IEbBT6jr5CbkuxyHEji
            M+KLsScIhIJ+sarcO/CieD281leZdZnzFEIMK0AscTj1meNe8lLPVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T15:26:47Z"
    mac: ENC[AES256_GCM,data:uDIOBBFfqe+JeQQZ3fIAM8dZdFF+XIOKmJvmHg19xpWmObcstilCH3pguKAxOioWmI5g3GiSetDLio2D3XMG4vjnZ5ByOtUN233f80OydySVWA7Hw4AZZUV53tpx4tbkm+q9657nY0ajynAgbP+Fo51x6LBUqzQohJ65cZQYIPE=,iv:fSMpy9W56fLbmN8s3oIeXCJp721VVtqfRmL+Q5tg7ac=,tag:v1vQwKVr7v2p+RTekPHl7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
