apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:xrOg1HtIDI83zoIqzc+ZUEHbiwXFQyga1fzfDv4xRyIPfYx4,iv:mpdYvJ3j7bZfQUfZ+tpAwyCwwc9d5Bl64A07x43M5h4=,tag:2rKg5G6mt8mLsRerCVlTRg==,type:str]
    credentials.json: ENC[AES256_GCM,data:8xvF/xNLKgXFryMaprKBIis1c6CE6sAEW4eCP2+qsdQq3pM5PGGYDLQnY/uQ+ZtewmOaWjRkINMtdwq9sAiN/iprYQPoIxk3kjVmNVPtJLp2Y+Cm/WkXK2d/h/nfive6bgnhNbWw+5a8c3JAvxU1p8KzOTGkMpgasF56syzh2Anp6tnZUdZmCBRQtuFDFl4qoQ++0um8vzU0EBJI1eT6bpUM2hAeW1pDHimnz5SWhg==,iv:oyD+yjKK9Dh9U12EsuXxsx0C+BwR96x6MIAl+rfLVdE=,tag:U/ewhF/US9k7dk1Ytgqkng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3h2frux0um302a9k8qww9ssmxkm9gjf4hs6crwyl9fd77n27duq5wq37y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeXJpVGRlcG85dlcvZktP
            TFBMQ3lzZlBDdkVXcmd5Zk9HcUV3RFpES3hVCjNuYldmdkRNZDdlT1ppWDdBaFZO
            K0dSNXNkbUlMMWVMdW1CQ3RJeUpQNEkKLS0tIGIxdmk1Zkc2NG91c1htbkxSUnFl
            TXRWSWRDa29nYk12OEpCN0N0RFQyL2cKR0owDgpnk4finT+3YKH5xK+e8fTxpAEC
            F50FLk2Q38jj2lrxBX6A4ZWUJleNoO/bOelIACe2CPVueA+/knMjpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T13:32:50Z"
    mac: ENC[AES256_GCM,data:xB2dKnwRGKluYBjML8eAkZZrqJNCtwKL834NTn0+j9DYxD1URXTfn2EyY9eHSoY9AthhxNP27SvG2r5cBfD5YdKXVtKObQesQmreCw43cJ27XYnVAq+m1YwaUjJNZT6f5rsnr4cIVM+hJh/JZ7WoaPVWA8cqbwn8xoUPTus+CDs=,iv:cwdjpSXhu8Fd9wCWL+0O7W84zKNLlb2hAhjq98f54Ds=,tag:thrNZRunKHTX0dG1IKUdaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
